### ISSUE TITLE
Point Cost

### ISSUE THREAD

**Issue by druidtekless** [danielloeblein/oathmark-army-builder#1]
The point cost listed in the book for dwarf spell casters is 30, 60, 110, 200, 270 
the points in your program read 50, 100, 200, 300, 400

Is there a way to fix stat lines on the user end?

**Comment by danielloeblein** [comment]
The point cost for dwarf spell casters is from the official errata:
https://drive.google.com/file/d/18vzREpST30kVexvO1_d_yT-zxwhryHlK/view

In general, if you have basic understanding of node, you can just clone the repository, change the army lists in src/terrains as you wish, and rebundle it with: npm run bundle
