### ISSUE TITLE
Special Formation Terrains

### ISSUE THREAD

**Issue by Bayard88** [danielloeblein/oathmark-army-builder#2]
Would be nice to add Special Formation Terrains from the Bane of Kings expansion
![Formations 1](https://user-images.githubusercontent.com/87723632/126387870-25667f1c-de92-4c52-af2c-2ef22757c348.PNG)
![Formations 2](https://user-images.githubusercontent.com/87723632/126387878-876c5b2b-d607-4752-93e5-123bf3471d3b.PNG)
![Formations 3](https://user-images.githubusercontent.com/87723632/126387888-7a8d4f4c-9931-42cd-af14-5fcce19e7940.PNG)
![Formations 4](https://user-images.githubusercontent.com/87723632/126387901-10429bd2-9624-49d3-955e-c869aad79bf0.PNG)
![Formations 5](https://user-images.githubusercontent.com/87723632/126387907-d42cc4ae-923f-4433-836b-11db306d69db.PNG)

**Comment by danielloeblein** [comment]
Done.
